### ISSUE TITLE
RecoverySpec failed

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#159]
This could be related to #157 as I've seen this failure already a second time after that PR but not before.

```
[recovery of D_3] Read metadata from remote replication endpoints ...
[recovery of D_3] Read clocks from local event logs ...
[recovery of D_3] Delete invalidated snapshots at local endpoint ...
[recovery of D_3] Checking replication progress with remote endpoints ...
[ERROR] [12/03/2015 15:09:56.345] [location-akka.actor.default-dispatcher-15] [akka.tcp://location@127.0.0.1:2553/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#931430359]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[ERROR] [12/03/2015 15:09:56.350] [location-akka.actor.default-dispatcher-4] [akka.tcp://location@127.0.0.1:2554/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#-1416672152]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[ERROR] [12/03/2015 15:09:56.362] [location-akka.actor.default-dispatcher-15] [akka.tcp://location@127.0.0.1:2552/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#2140128214]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[recovery of D_3] Trigger update of inconsistent replication progress at B_3_L1 ...
[recovery of D_3] Trigger update of inconsistent replication progress at C_3_L1 ...
[recovery of D_3] Trigger update of inconsistent replication progress at A_3_L1 ...
[recovery of D_3] Confirm existence of consistent replication progress at B_3_L1 (1 of 3) ...
[recovery of D_3] Confirm existence of consistent replication progress at C_3_L1 (2 of 3) ...
[recovery of D_3] Confirm existence of consistent replication progress at A_3_L1 (3 of 3) ...
[info] - must repair inconsistencies of an endpoint that has lost all events *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg while waiting for Set(a, b, c, d1, d)
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$assertConvergence$1.apply(RecoverySpec.scala:94)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$assertConvergence$1.apply(RecoverySpec.scala:94)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec.assertConvergence(RecoverySpec.scala:94)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply$mcV$sp(RecoverySpec.scala:159)
[info]   ...
```

**Comment by krasserm** [comment]
Failed again in [build 458](https://travis-ci.org/RBMHTechnology/eventuate/builds/94859848#L799).

```
[ERROR] [12/04/2015 12:24:37.905] [location-akka.actor.default-dispatcher-5] [akka.tcp://location@127.0.0.1:2552/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#-403574713]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[ERROR] [12/04/2015 12:24:37.908] [location-akka.actor.default-dispatcher-3] [akka.tcp://location@127.0.0.1:2554/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#1977293910]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[ERROR] [12/04/2015 12:24:37.911] [location-akka.actor.default-dispatcher-19] [akka.tcp://location@127.0.0.1:2553/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2555/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#574709185]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[recovery of D_4] Trigger update of inconsistent replication progress at C_4_L1 ...
[recovery of D_4] Trigger update of inconsistent replication progress at A_4_L1 ...
[recovery of D_4] Trigger update of inconsistent replication progress at B_4_L1 ...
[recovery of D_4] Confirm existence of consistent replication progress at B_4_L1 (1 of 3) ...
[recovery of D_4] Confirm existence of consistent replication progress at C_4_L1 (2 of 3) ...
[recovery of D_4] Confirm existence of consistent replication progress at A_4_L1 (3 of 3) ...
[info] - must repair inconsistencies of an endpoint that has lost all events *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at com.rbmhtechnology.eventuate.utilities.package$AwaitHelper.await(package.scala:17)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(RecoverySpec.scala:176)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(RecoverySpec.scala:136)
[info]   at com.rbmhtechnology.eventuate.RecoverySpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(RecoverySpec.scala:136)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   ...
```

**Comment by krasserm** [comment]
[Second failure](https://travis-ci.org/RBMHTechnology/eventuate/builds/94859848#L855) in same build.

```
[ERROR] [12/04/2015 12:24:47.553] [location-akka.actor.default-dispatcher-2] [akka.tcp://location@127.0.0.1:2553/user/$b/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@127.0.0.1:2552/), Path(/user/acceptor)]] after [2000 ms]. Sender[Actor[akka://location/user/$b/$a#-1244877196]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
[ERROR] [12/04/2015 12:24:47.600] [location-akka.remote.default-remote-dispatcher-5] [akka.tcp://location@127.0.0.1:2553/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Flocation%40127.0.0.1%3A2552-2/endpointWriter] AssociationError [akka.tcp://location@127.0.0.1:2553] <- [akka.tcp://location@127.0.0.1:2552]: Error [Shut down address: akka.tcp://location@127.0.0.1:2552] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://location@127.0.0.1:2552
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
]
[recovery of A_5] Read metadata from remote replication endpoints ...
[recovery of A_5] Read clocks from local event logs ...
[info] - must repair inconsistencies if recovery was stopped and restarted *** FAILED ***
[info]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://location/user/$a#1638685189]] after [1000 ms]. Sender[null] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$GetEventLogClock$".
[info]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:415)
[info]   at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:132)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
[info]   at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
[info]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:486)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:438)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:442)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:394)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   ...
```

**Comment by krasserm** [comment]
The two failures, reported above after having re-opened this issue, are based on a version that is subject to the issues described in [this commit comment](https://github.com/RBMHTechnology/eventuate/pull/162#commitcomment-14801908) (which is part of #162). However, I didn't investigate if they are actually related.
