### ISSUE TITLE
Document how to handle Cassandra batch size warnings and errors

### ISSUE THREAD

**Issue by kongo2002** [RBMHTechnology/eventuate#166]
In case of network partitions or other kind of failures over a reasonable amount of time (and maybe even combined with event DTOs with large serialization payloads) eventuate might get stuck on a batch size that is too large for akka remoting to be sent.

Right now there is no other possibility than to increase the configuration values for [batch replication](http://rbmhtechnology.github.io/eventuate/reference/event-log.html#batch-replication) and **restart the application**.

Based on some basic tests these are the exceptions of sender and receiver of the replication protocol:

#### sender

```
[info] [ERROR] [12/08/2015 13:36:08.492] [location-akka.remote.default-remote-dispatcher-6] [akka.tcp://location@chaos2.sbt.docker:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Flocation%40chaos3.sbt.docker%3A2552-29/endpointWriter] Transient association error (association remains live)
[info] akka.remote.OversizedPayloadException: Discarding oversized payload sent to Actor[akka.tcp://location@chaos3.sbt.docker:2552/temp/$h]: max allowed size 128000 bytes, actual size of encoded class com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadSuccess was 225063 bytes.
```

#### receiver

```
[info] [ERROR] [12/08/2015 13:09:26.807] [location-akka.actor.default-dispatcher-1067] [akka.tcp://location@chaos2.sbt.docker:2552/user/$c/$a] replication read failed: Ask timed out on [ActorSelection[Anchor(akka.tcp://location@chaos3.sbt.docker:2552/), Path(/user/acceptor)]] after [10000 ms]. Sender[Actor[akka://location/user/$c/$a#733245998]] sent message of type "com.rbmhtechnology.eventuate.ReplicationProtocol$ReplicationReadEnvelope".
```

Some kind of *dynamic batch resizing* might help in failure scenarios like this.

Cheers,
Gregor

**Comment by krasserm** [comment]
Absolutely agree, thanks @kongo2002.

**Comment by kongo2002** [comment]
I just want to add another very similar problematic behavior as the solution might be applicable to both cases. It appears that *index updates* do have the same problem as the cassandra driver throws an `InvalidQueryException: Batch too large` exception if the index update operation exceeds a limit. As of now I have to modify the configuration and **restart the application** to solve the problem.

This is the exception I just got at hand:

```
[ERROR] [12/10/2015 12:49:52.733] [location-akka.actor.default-dispatcher-289] [akka.tcp://location@location2.sbt.docker:2552/user/$a/$a/$b] UpdateIndex failure
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: Batch too large
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.rbmhtechnology.eventuate.log.cassandra.package$$anon$1$$anonfun$run$1.apply(package.scala:30)
        at scala.util.Try$.apply(Try.scala:192)
        at com.rbmhtechnology.eventuate.log.cassandra.package$$anon$1.run(package.scala:30)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Batch too large
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:103)
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:140)
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:293)
        at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:455)
        at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:734)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
```

**Comment by krasserm** [comment]
I see, thanks for reporting. I think it makes sense to prioritize this ticket then.

**Comment by krasserm** [comment]
I just renamed the ticket to better reflect how to deal with the reported issues. Instead of defining batch sizes in number of events, batch sizes should be defined in `kB` to better match the constraints of storage backends. This is not only relevant for the [Cassandra storage backend](http://rbmhtechnology.github.io/eventuate/reference/event-log.html#cassandra-storage-backend) but also relevant for a later Apache Kafka integration.

Places where batch sizes must constrained are:

- emission of new events by event-sourced actors and processors
- replication of events between location
- batch updates of event log indices

**Comment by krasserm** [comment]
As described in [CASSANDRA-8825](https://issues.apache.org/jira/browse/CASSANDRA-8825), batch size limits are only relevant for multi-partition updates. Since Eventuate makes only single-partition writes, the recommended strategy is to increase `batch_size_warn_threshold_in_kb` and `batch_size_fail_threshold_in_kb` in `cassandra.yaml` rather than limiting batch sizes in Eventuate applications too strictly.
