### ISSUE TITLE
User stash operations do not work properly

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#182]
A [small change](https://github.com/RBMHTechnology/eventuate/commit/345334ef1c5c15bacdd68a93986ae585a594cf5e) to the stashing tests of `EventsourcedActorSpec` revealed the following failure which occurs under certain race conditions:

```
[info] EventsourcedActorSpec:
[info] An EventsourcedActor
[info]   when in stateSync = true mode
[info]   ...
[info]   - must support user stash operations *** FAILED ***
[info]     java.lang.AssertionError: assertion failed: expected Pong(3), found d-1
[info]     at scala.Predef$.assert(Predef.scala:165)
[info]     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:351)
[info]     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]     at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(EventsourcedActorSpec.scala:327)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply(EventsourcedActorSpec.scala:290)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply(EventsourcedActorSpec.scala:290)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     ...
[ERROR] [12/28/2015 10:41:05.929] [test-akka.actor.default-dispatcher-2] [akka://test/user/$d] boom (com.rbmhtechnology.eventuate.package$$anon$1)
[info]   - ...
```

This failure can be reproduced in every run by placing [this write processing](https://github.com/RBMHTechnology/eventuate/blob/345334ef1c5c15bacdd68a93986ae585a594cf5e/src/test/scala/com/rbmhtechnology/eventuate/EventsourcedActorSpec.scala#L313) immediately before [that write processing](https://github.com/RBMHTechnology/eventuate/blob/345334ef1c5c15bacdd68a93986ae585a594cf5e/src/test/scala/com/rbmhtechnology/eventuate/EventsourcedActorSpec.scala#L318) in the test.

**Comment by krasserm** [comment]
User stash operations that interleave with internal stash operations may wrongly re-order messages. For example, this can occur when user stash operations are made while an asynchronous `persist` is running (and `stateSync` is set to `true`). A [minimal test case has been added](https://github.com/RBMHTechnology/eventuate/commit/8528e28679213ae6ea42123c860d3f8809f21f71) that demonstrates the problem. It currently fails with

```
[info] EventsourcedActorSpec:
[info] An EventsourcedActor
[info]   when in stateSync = true mode
[info]   ...
[info]   - must keep relative order of messages on internal and user stash (#182) *** FAILED ***
[info]     java.lang.AssertionError: assertion failed: expected Pong(1), found Pong(3)
[info]     at scala.Predef$.assert(Predef.scala:165)
[info]     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:351)
[info]     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]     at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(EventsourcedActorSpec.scala:346)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(EventsourcedActorSpec.scala:330)
[info]     at com.rbmhtechnology.eventuate.EventsourcedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(EventsourcedActorSpec.scala:330)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     ...
```

The problem is that the user stash and the internal stash of an event-sourced actor are independent. What is needed is a hierarchical stash where the internal stash controls the user stash.
