### ISSUE TITLE
EventsourcedActorIntegrationSpec failure

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#5]
[info] Eventsourced actors and views
    [info] - must support conditional command processing *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: expected a, found delayed-2
    [info]   at scala.Predef$.assert(Predef.scala:165)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply$mcV$sp(EventsourcedActorIntegrationSpec.scala:237)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(EventsourcedActorIntegrationSpec.scala:214)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(EventsourcedActorIntegrationSpec.scala:214)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    [info]   ...

**Comment by krasserm** [comment]
[info] - must support conditional command processing *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: expected a, found delayed-2
    [info]   at scala.Predef$.assert(Predef.scala:165)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$9.apply$mcV$sp(EventsourcedActorIntegrationSpec.scala:282)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$9.apply(EventsourcedActorIntegrationSpec.scala:262)
    [info]   at com.rbmhtechnology.eventuate.EventsourcedActorIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$9.apply(EventsourcedActorIntegrationSpec.scala:262)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    [info]   ...
