### ISSUE TITLE
Investigate LevelDB shutdown failures on Travis CI

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#87]
- mostly causes `it` tests to fail such as [this one](https://travis-ci.org/RBMHTechnology/eventuate/builds/69133047#L1869).
- error message is `pthread lock: invalid argument` from native code

**Comment by krasserm** [comment]
<pre>
pthread lock: Invalid argument
Exception in thread "Thread-161" Exception in thread "Thread-165" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:744)
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:906)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:895)
	at java.lang.Thread.run(Thread.java:744)
</pre>

**Comment by krasserm** [comment]
The problem is related to iterators that are still used by the read dispatcher. Tracking these iterators and closing them on event log shutdown however causes:

<pre>
libc++abi.dylib: Pure virtual function called!
Exception in thread "Thread-77" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:744)
Exception in thread "Thread-81" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:906)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:895)
	at java.lang.Thread.run(Thread.java:744)
</pre>
